### ISSUE TITLE
Sphinx & Restructured text for codes from Numpydoc V1.2.

### ISSUE THREAD

**Issue by Joseph-Wandji** [kaufmanno/GSDMA#22] opened 2020-11-13 13:25 UTC
This one has been closed because another issue is created in [Review the table of contents of the documentation](https://github.com/kaufmanno/GSDMA/issues/10)

**Comment by kaufmanno** [comment] 2020-11-22 11:51
@Joseph-Wandji Could you review your comment? It seems a verb is missing and this issue refers to itself...

**Comment by kaufmanno** [comment] 2020-11-27 16:49
Duplicate of issue #35? @Joseph-Wandji can we close this one?

**Closed** 2020-11-27 16:50 UTC
Labels: duplicate
